# enviroment settings
    
image:
  - Visual Studio 2019
  - macOS

# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

build_script:
  - mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -q

  # verify artifacts
test_script:
  - mvn verify -B -Dmaven.javadoc.skip=true -Djacoco.skip=true -ntp

for:
-
    matrix:
      only:
      - image: macOS
    cache:
      - '/usr/local/Cellar/maven/'

    install:
        #- brew install maven >/dev/null
        - brew link maven@3.6
        - export M2_HOME=/usr/local/Cellar/maven/3.6.3
        - /usr/libexec/java_home -V
        - export JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0_252)
        - export PATH=$M2_HOME:$PATH
        - export PATH=$JAVA_HOME:$PATH
-
    matrix:
      only:
      - image: Visual Studio 2019
    cache:
      - '%USERPROFILE%\.m2'


    environment:
        matrix:
            - JAVA_HOME: /Program Files/Java/jdk1.8.0
